# Generated by Django 3.1.7 on 2024-01-12 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_auto_20210408_1117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('address', models.CharField(max_length=300, verbose_name='Name')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='drclinic',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='appointments.clinic'),
            preserve_default=False,
        ),
    ]
