# Generated by Django 3.1.7 on 2024-01-12 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_auto_20240112_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='drclinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.clinic'),
        ),
    ]
